[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/api/bitbot"
to = "/.netlify/functions/bitbot"
status = 200

[[redirects]]
from = "/api/bitbot/*"
to = "/.netlify/functions/bitbot/:splat"
status = 200